"""
Rule-based Lending Decision Engine.
Deterministic logic to generate lending assessments based on ML risk scores
and borrower profiles, used as a non-LLM alternative for core logic.
"""

from typing import Any, Dict, List

def generate_lending_assessment(
    borrower_profile: Dict[str, Any],
    risk_score: float,
    risk_label: str,
    top_features: List[tuple],
    policy_chunks: List[Dict] = None
) -> Dict[str, str]:
    """
    Generate a deterministic, rule-based report.
    
    Parameters
    ----------
    borrower_profile : Dict
        Input form values.
    risk_score : float
        ML probability [0, 1].
    risk_label : str
        Human-readable classification.
    top_features : List
        SHAP or global importances.
    policy_chunks : List, optional
        Retrieved RAG snippets.
        
    Returns
    -------
    Dict[str, str]
        Structured report keys.
    """
    score = risk_score
    label = risk_label
    profile = borrower_profile

    # Decision Logic based on thresholds
    if score >= 0.50:
        decision = "DECLINE"
        rationale = (
            f"The ML model assigns a {score:.1%} default probability, exceeding the "
            "institution's 50% maximum threshold for standard lending. The elevated "
            "delinquency history and high credit utilization further support this decision."
        )
        mitigation = (
            "Improve revolving utilization below 30% over the next 12 months. "
            "Demonstrate 12 consecutive months of on-time payments. "
            "Consider credit counselling to reduce the debt-to-income ratio below 43%."
        )
    elif score >= 0.30:
        decision = "CONDITIONAL APPROVE"
        rationale = (
            f"The default probability of {score:.1%} is elevated (30–50% range). "
            "Conditional approval may be extended subject to compensating factors such as "
            "co-signer, collateral, or reduced loan amount (≤70% of requested)."
        )
        mitigation = (
            "Require a creditworthy co-signer or appropriate collateral. "
            "Cap credit limit at 70% of the requested amount. "
            "Enrol in monthly auto-debit repayment and conduct quarterly account reviews."
        )
    else:
        decision = "APPROVE"
        rationale = (
            f"The default probability of {score:.1%} is within the acceptable low-risk "
            "range (<30%). Repayment history and financial profile support standard approval."
        )
        mitigation = (
            "Standard annual account review applies. "
            "Monitor for any increase in revolving utilization above 60%."
        )

    top_factors = ", ".join(f[0].replace("_", " ") for f in top_features[:3])

    # Construct the report with RAG context if available
    ref_text = "Internal Credit Assessment Standards v2.3; Risk Threshold & Decision Policy; "
    if policy_chunks:
        policy_refs = "; ".join(set(c.get('source', 'policy') for c in policy_chunks))
        ref_text += policy_refs
    else:
        ref_text += "Fair Lending Compliance Policy; Basel III Framework."

    return {
        "profile_summary": (
            f"Borrower aged {profile.get('age', 'N/A')} with monthly income of "
            f"${profile.get('monthly_inc', 0):,.0f} and {profile.get('dependents', 0)} "
            f"dependent(s). Revolving utilization: {profile.get('rev_util', 0):.2f}. "
            f"Debt ratio: {profile.get('debt_ratio', 0):.2f}."
        ),
        "risk_analysis": (
            f"The ML model classifies this applicant "
            f"as **{label}** with a {score:.2%} probability of delinquency within 2 years. "
            f"Primary risk drivers: {top_factors}."
        ),
        "decision": decision,
        "decision_rationale": rationale,
        "risk_mitigation": mitigation,
        "references": ref_text,
        "disclaimer": (
            "This assessment is generated by a rule-based engine. "
            "Final lending decisions must be reviewed by a licensed credit professional."
        ),
    }
